server:
  port: 7856
  max-http-header-size: 102400

spring:
  datasource:
    url: jdbc:mysql://110.41.176.195:3306/crp?useSSL=false
    username: crp
    password: sC6jJstDhKKfysZ8

  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
  configuration:
    #关闭配置数据库下划线字段转驼峰
    map-underscore-to-camel-case: false

